### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by Jogai** [droidsolutions/asp-auth-claim-binder#282]
Looking at the releases you can see on the 1.2.0 releast that there are `414 commits to main since this release`. Since the whole project is a bit over 500 commits it looks like the nuget release is a bit behind. Is there any reasoning about releases? Are new releases scheduled?

**Comment by Jogai** [comment]
Thanks. I'm not missing anything. I actually digged some deeper and saw that the 400 commits amounts to almost nothing. Its just that on quick inspection there seems to be a big discrepancy between commits and releases. More releases make the project look better (even if it is superficial to measure a project agains such stats).

**Comment by Kampfmoehre** [comment]
Yes I know how those stats are used to find projects.
This was just some thing that I needed in a project and then I needed it in another one so I made a NuGet package out of it. And then I needed it in a hobby project so I just made it open source in case someone other might find it useful.

We use Dependabot to keep all deps up to date though in this project it doesn't really matter since there are mostly dev deps. Since we are using Semantic Release we have some JS dependencies and in the JS world deps move a lot faster. This is where all those commits come from mostly.

If you need it I can release a new version explicitly supporting .NET 8.

**Comment by Jogai** [comment]
Thanks! That would be nice. We could use it in a fresh project. We had the same thing. Used in one, needed in another. I actually told my colleague to open source it, but then we found this one.

**Comment by Kampfmoehre** [comment]
I published [v2.0.1](https://www.nuget.org/packages/DroidSolutions.Oss.AuthClaimBinder) which supports .NET 8 and dropped support for .NET 7 since it is no longer supported by Microsoft.

**Comment by Jogai** [comment]
Thanks for moving that fast!
